<?xml version="1.0" encoding="utf-8"?><Database Name="dbGC" Class="GiftCheckDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=dbGC;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="connGC" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Dining" Member="Dinings">
    <Type Name="Dining">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Dining_GCDining" Member="GCDinings" ThisKey="Id" OtherKey="DiningId" Type="GCDining" />
    </Type>
  </Table>
  <Table Name="dbo.Room" Member="Rooms">
    <Type Name="Room">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Room" Member="Room1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Regular" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Peak" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Room_GCRoom" Member="GCRooms" ThisKey="Id" OtherKey="RoomId" Type="GCRoom" />
    </Type>
  </Table>
  <Table Name="dbo.Guest" Member="Guests">
    <Type Name="Guest">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GuestId" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ValidIDNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PicFilePath" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IDFilePath" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EmergencyContactPerson" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmergencyContactNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmergencyContactAddress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Guest_GCTransaction" Member="GCTransactions" ThisKey="GuestId" OtherKey="GuestId" Type="GCTransaction" />
    </Type>
  </Table>
  <Table Name="dbo.GCTransaction" Member="GCTransactions">
    <Type Name="GCTransaction">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GCNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GuestId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RecommendingApproval" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="AccountNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ArrivalDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CheckOutDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="GCTransaction_GCDining" Member="GCDinings" ThisKey="Id" OtherKey="GCTransactionId" Type="GCDining" />
      <Association Name="GCTransaction_GCRoom" Member="GCRooms" ThisKey="Id" OtherKey="GCTransactionId" Type="GCRoom" />
      <Association Name="Guest_GCTransaction" Member="Guest" ThisKey="GuestId" OtherKey="GuestId" Type="Guest" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.GCDining" Member="GCDinings">
    <Type Name="GCDining">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GCTransactionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiningId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Dining_GCDining" Member="Dining" ThisKey="DiningId" OtherKey="Id" Type="Dining" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="GCTransaction_GCDining" Member="GCTransaction" ThisKey="GCTransactionId" OtherKey="Id" Type="GCTransaction" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.GCRoom" Member="GCRooms">
    <Type Name="GCRoom">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GCTransactionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoomId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nights" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="GCTransaction_GCRoom" Member="GCTransaction" ThisKey="GCTransactionId" OtherKey="Id" Type="GCTransaction" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Room_GCRoom" Member="Room" ThisKey="RoomId" OtherKey="Id" Type="Room" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.tmpRoom" Member="tmpRooms">
    <Type Name="tmpRoom">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="RoomId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Night" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
</Database>