<?xml version="1.0" encoding="utf-8"?><Database Name="dbGC" Class="GiftCheckDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=dbGC;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="connGC" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Dining" Member="Dinings">
    <Type Name="Dining">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Dining_GCRoom" Member="GCRooms" ThisKey="Id" OtherKey="DiningId" Type="GCRoom" />
    </Type>
  </Table>
  <Table Name="dbo.GCRoom" Member="GCRooms">
    <Type Name="GCRoom">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GCTransactionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoomId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiningId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nights" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Dining_GCRoom" Member="Dining" ThisKey="DiningId" OtherKey="Id" Type="Dining" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="GCTransaction_GCRoom" Member="GCTransaction" ThisKey="GCTransactionId" OtherKey="Id" Type="GCTransaction" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Room_GCRoom" Member="Room" ThisKey="RoomId" OtherKey="Id" Type="Room" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Memberships" Member="MembershipLINQs">
    <Type Name="MembershipLINQ">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowsStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="User_MembershipLINQ" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="Role_UsersInRole" Member="UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="UsersInRole" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_MembershipLINQ" Member="MembershipLINQ" ThisKey="UserId" OtherKey="UserId" Type="MembershipLINQ" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.UsersInRoles" Member="UsersInRoles">
    <Type Name="UsersInRole">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_UsersInRole" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Guest" Member="Guests">
    <Type Name="Guest">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GuestId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ValidIDNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PicFilePath" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IDFilePath" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EmergencyContactPerson" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmergencyContactNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmergencyContactAddress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsCompany" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Guest_GCTransaction" Member="GCTransactions" ThisKey="Id" OtherKey="GuestId" Type="GCTransaction" />
    </Type>
  </Table>
  <Table Name="dbo.GCTransaction" Member="GCTransactions">
    <Type Name="GCTransaction">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GuestId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GCNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RecommendingApproval" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="AccountNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ArrivalDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CheckOutDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ApprovalStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StatusGC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CancellationReason" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CancelledDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsArchive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="GCTransaction_GCRoom" Member="GCRooms" ThisKey="Id" OtherKey="GCTransactionId" Type="GCRoom" />
      <Association Name="Guest_GCTransaction" Member="Guest" ThisKey="GuestId" OtherKey="Id" Type="Guest" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Room" Member="Rooms">
    <Type Name="Room">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Room" Member="Room1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Room_GCRoom" Member="GCRooms" ThisKey="Id" OtherKey="RoomId" Type="GCRoom" />
    </Type>
  </Table>
  <Table Name="dbo.tmpRoom" Member="tmpRooms">
    <Type Name="tmpRoom">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="RoomId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiningId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>