#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbGC")]
	public partial class GiftCheckDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGuest(Guest instance);
    partial void UpdateGuest(Guest instance);
    partial void DeleteGuest(Guest instance);
    partial void InsertStatusSite(StatusSite instance);
    partial void UpdateStatusSite(StatusSite instance);
    partial void DeleteStatusSite(StatusSite instance);
    partial void InsertDining(Dining instance);
    partial void UpdateDining(Dining instance);
    partial void DeleteDining(Dining instance);
    partial void InsertDiningType(DiningType instance);
    partial void UpdateDiningType(DiningType instance);
    partial void DeleteDiningType(DiningType instance);
    partial void InsertAuditTrail(AuditTrail instance);
    partial void UpdateAuditTrail(AuditTrail instance);
    partial void DeleteAuditTrail(AuditTrail instance);
    partial void InsertRoom(Room instance);
    partial void UpdateRoom(Room instance);
    partial void DeleteRoom(Room instance);
    partial void InsertGCTransaction(GCTransaction instance);
    partial void UpdateGCTransaction(GCTransaction instance);
    partial void DeleteGCTransaction(GCTransaction instance);
    partial void InserttmpRoom(tmpRoom instance);
    partial void UpdatetmpRoom(tmpRoom instance);
    partial void DeletetmpRoom(tmpRoom instance);
    #endregion
		
		public GiftCheckDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["connGC"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GiftCheckDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GiftCheckDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GiftCheckDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GiftCheckDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Guest> Guests
		{
			get
			{
				return this.GetTable<Guest>();
			}
		}
		
		public System.Data.Linq.Table<StatusSite> StatusSites
		{
			get
			{
				return this.GetTable<StatusSite>();
			}
		}
		
		public System.Data.Linq.Table<Dining> Dinings
		{
			get
			{
				return this.GetTable<Dining>();
			}
		}
		
		public System.Data.Linq.Table<DiningType> DiningTypes
		{
			get
			{
				return this.GetTable<DiningType>();
			}
		}
		
		public System.Data.Linq.Table<AuditTrail> AuditTrails
		{
			get
			{
				return this.GetTable<AuditTrail>();
			}
		}
		
		public System.Data.Linq.Table<Room> Rooms
		{
			get
			{
				return this.GetTable<Room>();
			}
		}
		
		public System.Data.Linq.Table<GCTransaction> GCTransactions
		{
			get
			{
				return this.GetTable<GCTransaction>();
			}
		}
		
		public System.Data.Linq.Table<tmpRoom> tmpRooms
		{
			get
			{
				return this.GetTable<tmpRoom>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Guest")]
	public partial class Guest : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _GuestId;
		
		private string _FirstName;
		
		private string _MiddleName;
		
		private string _LastName;
		
		private string _CompanyName;
		
		private string _ContactNumber;
		
		private string _Email;
		
		private string _ValidIDNumber;
		
		private string _PicFilePath;
		
		private string _IDFilePath;
		
		private string _EmergencyContactPerson;
		
		private string _EmergencyContactNumber;
		
		private string _EmergencyContactAddress;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreatedBy;
		
		private System.Nullable<bool> _IsCompany;
		
		private System.Nullable<int> _CompanyId;
		
		private EntitySet<GCTransaction> _GCTransactions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGuestIdChanging(string value);
    partial void OnGuestIdChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnContactNumberChanging(string value);
    partial void OnContactNumberChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnValidIDNumberChanging(string value);
    partial void OnValidIDNumberChanged();
    partial void OnPicFilePathChanging(string value);
    partial void OnPicFilePathChanged();
    partial void OnIDFilePathChanging(string value);
    partial void OnIDFilePathChanged();
    partial void OnEmergencyContactPersonChanging(string value);
    partial void OnEmergencyContactPersonChanged();
    partial void OnEmergencyContactNumberChanging(string value);
    partial void OnEmergencyContactNumberChanged();
    partial void OnEmergencyContactAddressChanging(string value);
    partial void OnEmergencyContactAddressChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnIsCompanyChanging(System.Nullable<bool> value);
    partial void OnIsCompanyChanged();
    partial void OnCompanyIdChanging(System.Nullable<int> value);
    partial void OnCompanyIdChanged();
    #endregion
		
		public Guest()
		{
			this._GCTransactions = new EntitySet<GCTransaction>(new Action<GCTransaction>(this.attach_GCTransactions), new Action<GCTransaction>(this.detach_GCTransactions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestId", DbType="VarChar(50)")]
		public string GuestId
		{
			get
			{
				return this._GuestId;
			}
			set
			{
				if ((this._GuestId != value))
				{
					this.OnGuestIdChanging(value);
					this.SendPropertyChanging();
					this._GuestId = value;
					this.SendPropertyChanged("GuestId");
					this.OnGuestIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="VarChar(100)")]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="VarChar(50)")]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this.OnContactNumberChanging(value);
					this.SendPropertyChanging();
					this._ContactNumber = value;
					this.SendPropertyChanged("ContactNumber");
					this.OnContactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidIDNumber", DbType="VarChar(50)")]
		public string ValidIDNumber
		{
			get
			{
				return this._ValidIDNumber;
			}
			set
			{
				if ((this._ValidIDNumber != value))
				{
					this.OnValidIDNumberChanging(value);
					this.SendPropertyChanging();
					this._ValidIDNumber = value;
					this.SendPropertyChanged("ValidIDNumber");
					this.OnValidIDNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFilePath", DbType="VarChar(MAX)")]
		public string PicFilePath
		{
			get
			{
				return this._PicFilePath;
			}
			set
			{
				if ((this._PicFilePath != value))
				{
					this.OnPicFilePathChanging(value);
					this.SendPropertyChanging();
					this._PicFilePath = value;
					this.SendPropertyChanged("PicFilePath");
					this.OnPicFilePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDFilePath", DbType="VarChar(MAX)")]
		public string IDFilePath
		{
			get
			{
				return this._IDFilePath;
			}
			set
			{
				if ((this._IDFilePath != value))
				{
					this.OnIDFilePathChanging(value);
					this.SendPropertyChanging();
					this._IDFilePath = value;
					this.SendPropertyChanged("IDFilePath");
					this.OnIDFilePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmergencyContactPerson", DbType="VarChar(50)")]
		public string EmergencyContactPerson
		{
			get
			{
				return this._EmergencyContactPerson;
			}
			set
			{
				if ((this._EmergencyContactPerson != value))
				{
					this.OnEmergencyContactPersonChanging(value);
					this.SendPropertyChanging();
					this._EmergencyContactPerson = value;
					this.SendPropertyChanged("EmergencyContactPerson");
					this.OnEmergencyContactPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmergencyContactNumber", DbType="VarChar(50)")]
		public string EmergencyContactNumber
		{
			get
			{
				return this._EmergencyContactNumber;
			}
			set
			{
				if ((this._EmergencyContactNumber != value))
				{
					this.OnEmergencyContactNumberChanging(value);
					this.SendPropertyChanging();
					this._EmergencyContactNumber = value;
					this.SendPropertyChanged("EmergencyContactNumber");
					this.OnEmergencyContactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmergencyContactAddress", DbType="VarChar(MAX)")]
		public string EmergencyContactAddress
		{
			get
			{
				return this._EmergencyContactAddress;
			}
			set
			{
				if ((this._EmergencyContactAddress != value))
				{
					this.OnEmergencyContactAddressChanging(value);
					this.SendPropertyChanging();
					this._EmergencyContactAddress = value;
					this.SendPropertyChanged("EmergencyContactAddress");
					this.OnEmergencyContactAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCompany", DbType="Bit")]
		public System.Nullable<bool> IsCompany
		{
			get
			{
				return this._IsCompany;
			}
			set
			{
				if ((this._IsCompany != value))
				{
					this.OnIsCompanyChanging(value);
					this.SendPropertyChanging();
					this._IsCompany = value;
					this.SendPropertyChanged("IsCompany");
					this.OnIsCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyId", DbType="Int")]
		public System.Nullable<int> CompanyId
		{
			get
			{
				return this._CompanyId;
			}
			set
			{
				if ((this._CompanyId != value))
				{
					this.OnCompanyIdChanging(value);
					this.SendPropertyChanging();
					this._CompanyId = value;
					this.SendPropertyChanged("CompanyId");
					this.OnCompanyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Guest_GCTransaction", Storage="_GCTransactions", ThisKey="Id", OtherKey="GuestId")]
		public EntitySet<GCTransaction> GCTransactions
		{
			get
			{
				return this._GCTransactions;
			}
			set
			{
				this._GCTransactions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GCTransactions(GCTransaction entity)
		{
			this.SendPropertyChanging();
			entity.Guest = this;
		}
		
		private void detach_GCTransactions(GCTransaction entity)
		{
			this.SendPropertyChanging();
			entity.Guest = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StatusSite")]
	public partial class StatusSite : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<bool> _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    #endregion
		
		public StatusSite()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dining")]
	public partial class Dining : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private EntitySet<GCTransaction> _GCTransactions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Dining()
		{
			this._GCTransactions = new EntitySet<GCTransaction>(new Action<GCTransaction>(this.attach_GCTransactions), new Action<GCTransaction>(this.detach_GCTransactions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dining_GCTransaction", Storage="_GCTransactions", ThisKey="Id", OtherKey="DiningId")]
		public EntitySet<GCTransaction> GCTransactions
		{
			get
			{
				return this._GCTransactions;
			}
			set
			{
				this._GCTransactions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GCTransactions(GCTransaction entity)
		{
			this.SendPropertyChanging();
			entity.Dining = this;
		}
		
		private void detach_GCTransactions(GCTransaction entity)
		{
			this.SendPropertyChanging();
			entity.Dining = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiningType")]
	public partial class DiningType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _DiningType1;
		
		private System.Nullable<bool> _Active;
		
		private EntitySet<GCTransaction> _GCTransactions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDiningType1Changing(string value);
    partial void OnDiningType1Changed();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public DiningType()
		{
			this._GCTransactions = new EntitySet<GCTransaction>(new Action<GCTransaction>(this.attach_GCTransactions), new Action<GCTransaction>(this.detach_GCTransactions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DiningType", Storage="_DiningType1", DbType="VarChar(MAX)")]
		public string DiningType1
		{
			get
			{
				return this._DiningType1;
			}
			set
			{
				if ((this._DiningType1 != value))
				{
					this.OnDiningType1Changing(value);
					this.SendPropertyChanging();
					this._DiningType1 = value;
					this.SendPropertyChanged("DiningType1");
					this.OnDiningType1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiningType_GCTransaction", Storage="_GCTransactions", ThisKey="Id", OtherKey="DiningTypeId")]
		public EntitySet<GCTransaction> GCTransactions
		{
			get
			{
				return this._GCTransactions;
			}
			set
			{
				this._GCTransactions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GCTransactions(GCTransaction entity)
		{
			this.SendPropertyChanging();
			entity.DiningType = this;
		}
		
		private void detach_GCTransactions(GCTransaction entity)
		{
			this.SendPropertyChanging();
			entity.DiningType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AuditTrail")]
	public partial class AuditTrail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _User;
		
		private string _Action;
		
		private string _Description;
		
		private string _AssociatedId;
		
		private System.Nullable<System.DateTime> _ActionDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserChanging(string value);
    partial void OnUserChanged();
    partial void OnActionChanging(string value);
    partial void OnActionChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnAssociatedIdChanging(string value);
    partial void OnAssociatedIdChanged();
    partial void OnActionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnActionDateChanged();
    #endregion
		
		public AuditTrail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="VarChar(50)")]
		public string User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this.OnUserChanging(value);
					this.SendPropertyChanging();
					this._User = value;
					this.SendPropertyChanged("User");
					this.OnUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action", DbType="VarChar(50)")]
		public string Action
		{
			get
			{
				return this._Action;
			}
			set
			{
				if ((this._Action != value))
				{
					this.OnActionChanging(value);
					this.SendPropertyChanging();
					this._Action = value;
					this.SendPropertyChanged("Action");
					this.OnActionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssociatedId", DbType="VarChar(50)")]
		public string AssociatedId
		{
			get
			{
				return this._AssociatedId;
			}
			set
			{
				if ((this._AssociatedId != value))
				{
					this.OnAssociatedIdChanging(value);
					this.SendPropertyChanging();
					this._AssociatedId = value;
					this.SendPropertyChanged("AssociatedId");
					this.OnAssociatedIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ActionDate
		{
			get
			{
				return this._ActionDate;
			}
			set
			{
				if ((this._ActionDate != value))
				{
					this.OnActionDateChanging(value);
					this.SendPropertyChanging();
					this._ActionDate = value;
					this.SendPropertyChanged("ActionDate");
					this.OnActionDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Room")]
	public partial class Room : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Type;
		
		private string _Room1;
		
		private EntitySet<GCTransaction> _GCTransactions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnRoom1Changing(string value);
    partial void OnRoom1Changed();
    #endregion
		
		public Room()
		{
			this._GCTransactions = new EntitySet<GCTransaction>(new Action<GCTransaction>(this.attach_GCTransactions), new Action<GCTransaction>(this.detach_GCTransactions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(MAX)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Room", Storage="_Room1", DbType="VarChar(MAX)")]
		public string Room1
		{
			get
			{
				return this._Room1;
			}
			set
			{
				if ((this._Room1 != value))
				{
					this.OnRoom1Changing(value);
					this.SendPropertyChanging();
					this._Room1 = value;
					this.SendPropertyChanged("Room1");
					this.OnRoom1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Room_GCTransaction", Storage="_GCTransactions", ThisKey="Id", OtherKey="RoomId")]
		public EntitySet<GCTransaction> GCTransactions
		{
			get
			{
				return this._GCTransactions;
			}
			set
			{
				this._GCTransactions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GCTransactions(GCTransaction entity)
		{
			this.SendPropertyChanging();
			entity.Room = this;
		}
		
		private void detach_GCTransactions(GCTransaction entity)
		{
			this.SendPropertyChanging();
			entity.Room = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GCTransaction")]
	public partial class GCTransaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _GuestId;
		
		private string _Property;
		
		private string _GCNumber;
		
		private System.Nullable<System.DateTime> _DateIssued;
		
		private string _GCType;
		
		private System.Nullable<System.DateTime> _ExpirationDate;
		
		private string _Remarks;
		
		private System.Nullable<System.Guid> _CreatedBy;
		
		private string _StatusGC;
		
		private System.Nullable<System.Guid> _ApprovedBy;
		
		private string _ApprovalStatus;
		
		private string _CancellationReason;
		
		private System.Nullable<System.DateTime> _CancelledDate;
		
		private System.Nullable<bool> _IsArchive;
		
		private System.Nullable<int> _RoomId;
		
		private System.Nullable<int> _DiningId;
		
		private System.Nullable<int> _DiningTypeId;
		
		private System.Nullable<bool> _WithBreakfast;
		
		private System.Nullable<int> _HeadCount;
		
		private System.Nullable<System.DateTime> _CheckinDate;
		
		private System.Nullable<System.DateTime> _CheckoutDate;
		
		private EntityRef<Dining> _Dining;
		
		private EntityRef<DiningType> _DiningType;
		
		private EntityRef<Guest> _Guest;
		
		private EntityRef<Room> _Room;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGuestIdChanging(System.Nullable<int> value);
    partial void OnGuestIdChanged();
    partial void OnPropertyChanging(string value);
    partial void OnPropertyChanged();
    partial void OnGCNumberChanging(string value);
    partial void OnGCNumberChanged();
    partial void OnDateIssuedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateIssuedChanged();
    partial void OnGCTypeChanging(string value);
    partial void OnGCTypeChanged();
    partial void OnExpirationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpirationDateChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnCreatedByChanging(System.Nullable<System.Guid> value);
    partial void OnCreatedByChanged();
    partial void OnStatusGCChanging(string value);
    partial void OnStatusGCChanged();
    partial void OnApprovedByChanging(System.Nullable<System.Guid> value);
    partial void OnApprovedByChanged();
    partial void OnApprovalStatusChanging(string value);
    partial void OnApprovalStatusChanged();
    partial void OnCancellationReasonChanging(string value);
    partial void OnCancellationReasonChanged();
    partial void OnCancelledDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCancelledDateChanged();
    partial void OnIsArchiveChanging(System.Nullable<bool> value);
    partial void OnIsArchiveChanged();
    partial void OnRoomIdChanging(System.Nullable<int> value);
    partial void OnRoomIdChanged();
    partial void OnDiningIdChanging(System.Nullable<int> value);
    partial void OnDiningIdChanged();
    partial void OnDiningTypeIdChanging(System.Nullable<int> value);
    partial void OnDiningTypeIdChanged();
    partial void OnWithBreakfastChanging(System.Nullable<bool> value);
    partial void OnWithBreakfastChanged();
    partial void OnHeadCountChanging(System.Nullable<int> value);
    partial void OnHeadCountChanged();
    partial void OnCheckinDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCheckinDateChanged();
    partial void OnCheckoutDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCheckoutDateChanged();
    #endregion
		
		public GCTransaction()
		{
			this._Dining = default(EntityRef<Dining>);
			this._DiningType = default(EntityRef<DiningType>);
			this._Guest = default(EntityRef<Guest>);
			this._Room = default(EntityRef<Room>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestId", DbType="Int")]
		public System.Nullable<int> GuestId
		{
			get
			{
				return this._GuestId;
			}
			set
			{
				if ((this._GuestId != value))
				{
					if (this._Guest.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGuestIdChanging(value);
					this.SendPropertyChanging();
					this._GuestId = value;
					this.SendPropertyChanged("GuestId");
					this.OnGuestIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property", DbType="VarChar(20)")]
		public string Property
		{
			get
			{
				return this._Property;
			}
			set
			{
				if ((this._Property != value))
				{
					this.OnPropertyChanging(value);
					this.SendPropertyChanging();
					this._Property = value;
					this.SendPropertyChanged("Property");
					this.OnPropertyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GCNumber", DbType="VarChar(50)")]
		public string GCNumber
		{
			get
			{
				return this._GCNumber;
			}
			set
			{
				if ((this._GCNumber != value))
				{
					this.OnGCNumberChanging(value);
					this.SendPropertyChanging();
					this._GCNumber = value;
					this.SendPropertyChanged("GCNumber");
					this.OnGCNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateIssued", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateIssued
		{
			get
			{
				return this._DateIssued;
			}
			set
			{
				if ((this._DateIssued != value))
				{
					this.OnDateIssuedChanging(value);
					this.SendPropertyChanging();
					this._DateIssued = value;
					this.SendPropertyChanged("DateIssued");
					this.OnDateIssuedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GCType", DbType="VarChar(50)")]
		public string GCType
		{
			get
			{
				return this._GCType;
			}
			set
			{
				if ((this._GCType != value))
				{
					this.OnGCTypeChanging(value);
					this.SendPropertyChanging();
					this._GCType = value;
					this.SendPropertyChanged("GCType");
					this.OnGCTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpirationDate", DbType="Date")]
		public System.Nullable<System.DateTime> ExpirationDate
		{
			get
			{
				return this._ExpirationDate;
			}
			set
			{
				if ((this._ExpirationDate != value))
				{
					this.OnExpirationDateChanging(value);
					this.SendPropertyChanging();
					this._ExpirationDate = value;
					this.SendPropertyChanged("ExpirationDate");
					this.OnExpirationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(MAX)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusGC", DbType="VarChar(50)")]
		public string StatusGC
		{
			get
			{
				return this._StatusGC;
			}
			set
			{
				if ((this._StatusGC != value))
				{
					this.OnStatusGCChanging(value);
					this.SendPropertyChanging();
					this._StatusGC = value;
					this.SendPropertyChanged("StatusGC");
					this.OnStatusGCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovedBy", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ApprovedBy
		{
			get
			{
				return this._ApprovedBy;
			}
			set
			{
				if ((this._ApprovedBy != value))
				{
					this.OnApprovedByChanging(value);
					this.SendPropertyChanging();
					this._ApprovedBy = value;
					this.SendPropertyChanged("ApprovedBy");
					this.OnApprovedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovalStatus", DbType="VarChar(50)")]
		public string ApprovalStatus
		{
			get
			{
				return this._ApprovalStatus;
			}
			set
			{
				if ((this._ApprovalStatus != value))
				{
					this.OnApprovalStatusChanging(value);
					this.SendPropertyChanging();
					this._ApprovalStatus = value;
					this.SendPropertyChanged("ApprovalStatus");
					this.OnApprovalStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CancellationReason", DbType="VarChar(MAX)")]
		public string CancellationReason
		{
			get
			{
				return this._CancellationReason;
			}
			set
			{
				if ((this._CancellationReason != value))
				{
					this.OnCancellationReasonChanging(value);
					this.SendPropertyChanging();
					this._CancellationReason = value;
					this.SendPropertyChanged("CancellationReason");
					this.OnCancellationReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CancelledDate", DbType="Date")]
		public System.Nullable<System.DateTime> CancelledDate
		{
			get
			{
				return this._CancelledDate;
			}
			set
			{
				if ((this._CancelledDate != value))
				{
					this.OnCancelledDateChanging(value);
					this.SendPropertyChanging();
					this._CancelledDate = value;
					this.SendPropertyChanged("CancelledDate");
					this.OnCancelledDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsArchive", DbType="Bit")]
		public System.Nullable<bool> IsArchive
		{
			get
			{
				return this._IsArchive;
			}
			set
			{
				if ((this._IsArchive != value))
				{
					this.OnIsArchiveChanging(value);
					this.SendPropertyChanging();
					this._IsArchive = value;
					this.SendPropertyChanged("IsArchive");
					this.OnIsArchiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomId", DbType="Int")]
		public System.Nullable<int> RoomId
		{
			get
			{
				return this._RoomId;
			}
			set
			{
				if ((this._RoomId != value))
				{
					if (this._Room.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoomIdChanging(value);
					this.SendPropertyChanging();
					this._RoomId = value;
					this.SendPropertyChanged("RoomId");
					this.OnRoomIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiningId", DbType="Int")]
		public System.Nullable<int> DiningId
		{
			get
			{
				return this._DiningId;
			}
			set
			{
				if ((this._DiningId != value))
				{
					if (this._Dining.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDiningIdChanging(value);
					this.SendPropertyChanging();
					this._DiningId = value;
					this.SendPropertyChanged("DiningId");
					this.OnDiningIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiningTypeId", DbType="Int")]
		public System.Nullable<int> DiningTypeId
		{
			get
			{
				return this._DiningTypeId;
			}
			set
			{
				if ((this._DiningTypeId != value))
				{
					if (this._DiningType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDiningTypeIdChanging(value);
					this.SendPropertyChanging();
					this._DiningTypeId = value;
					this.SendPropertyChanged("DiningTypeId");
					this.OnDiningTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WithBreakfast", DbType="Bit")]
		public System.Nullable<bool> WithBreakfast
		{
			get
			{
				return this._WithBreakfast;
			}
			set
			{
				if ((this._WithBreakfast != value))
				{
					this.OnWithBreakfastChanging(value);
					this.SendPropertyChanging();
					this._WithBreakfast = value;
					this.SendPropertyChanged("WithBreakfast");
					this.OnWithBreakfastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeadCount", DbType="Int")]
		public System.Nullable<int> HeadCount
		{
			get
			{
				return this._HeadCount;
			}
			set
			{
				if ((this._HeadCount != value))
				{
					this.OnHeadCountChanging(value);
					this.SendPropertyChanging();
					this._HeadCount = value;
					this.SendPropertyChanged("HeadCount");
					this.OnHeadCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckinDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CheckinDate
		{
			get
			{
				return this._CheckinDate;
			}
			set
			{
				if ((this._CheckinDate != value))
				{
					this.OnCheckinDateChanging(value);
					this.SendPropertyChanging();
					this._CheckinDate = value;
					this.SendPropertyChanged("CheckinDate");
					this.OnCheckinDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckoutDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CheckoutDate
		{
			get
			{
				return this._CheckoutDate;
			}
			set
			{
				if ((this._CheckoutDate != value))
				{
					this.OnCheckoutDateChanging(value);
					this.SendPropertyChanging();
					this._CheckoutDate = value;
					this.SendPropertyChanged("CheckoutDate");
					this.OnCheckoutDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dining_GCTransaction", Storage="_Dining", ThisKey="DiningId", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public Dining Dining
		{
			get
			{
				return this._Dining.Entity;
			}
			set
			{
				Dining previousValue = this._Dining.Entity;
				if (((previousValue != value) 
							|| (this._Dining.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dining.Entity = null;
						previousValue.GCTransactions.Remove(this);
					}
					this._Dining.Entity = value;
					if ((value != null))
					{
						value.GCTransactions.Add(this);
						this._DiningId = value.Id;
					}
					else
					{
						this._DiningId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Dining");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiningType_GCTransaction", Storage="_DiningType", ThisKey="DiningTypeId", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public DiningType DiningType
		{
			get
			{
				return this._DiningType.Entity;
			}
			set
			{
				DiningType previousValue = this._DiningType.Entity;
				if (((previousValue != value) 
							|| (this._DiningType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiningType.Entity = null;
						previousValue.GCTransactions.Remove(this);
					}
					this._DiningType.Entity = value;
					if ((value != null))
					{
						value.GCTransactions.Add(this);
						this._DiningTypeId = value.Id;
					}
					else
					{
						this._DiningTypeId = default(Nullable<int>);
					}
					this.SendPropertyChanged("DiningType");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Guest_GCTransaction", Storage="_Guest", ThisKey="GuestId", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public Guest Guest
		{
			get
			{
				return this._Guest.Entity;
			}
			set
			{
				Guest previousValue = this._Guest.Entity;
				if (((previousValue != value) 
							|| (this._Guest.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Guest.Entity = null;
						previousValue.GCTransactions.Remove(this);
					}
					this._Guest.Entity = value;
					if ((value != null))
					{
						value.GCTransactions.Add(this);
						this._GuestId = value.Id;
					}
					else
					{
						this._GuestId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Guest");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Room_GCTransaction", Storage="_Room", ThisKey="RoomId", OtherKey="Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public Room Room
		{
			get
			{
				return this._Room.Entity;
			}
			set
			{
				Room previousValue = this._Room.Entity;
				if (((previousValue != value) 
							|| (this._Room.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Room.Entity = null;
						previousValue.GCTransactions.Remove(this);
					}
					this._Room.Entity = value;
					if ((value != null))
					{
						value.GCTransactions.Add(this);
						this._RoomId = value.Id;
					}
					else
					{
						this._RoomId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Room");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tmpRoom")]
	public partial class tmpRoom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.Guid> _UserId;
		
		private string _Property;
		
		private System.Nullable<int> _RoomId;
		
		private System.Nullable<int> _DiningId;
		
		private System.Nullable<bool> _WithBreakfast;
		
		private System.Nullable<int> _HeadCount;
		
		private System.Nullable<int> _DiningTypeId;
		
		private string _GCNumber;
		
		private string _Remarks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(System.Nullable<System.Guid> value);
    partial void OnUserIdChanged();
    partial void OnPropertyChanging(string value);
    partial void OnPropertyChanged();
    partial void OnRoomIdChanging(System.Nullable<int> value);
    partial void OnRoomIdChanged();
    partial void OnDiningIdChanging(System.Nullable<int> value);
    partial void OnDiningIdChanged();
    partial void OnWithBreakfastChanging(System.Nullable<bool> value);
    partial void OnWithBreakfastChanged();
    partial void OnHeadCountChanging(System.Nullable<int> value);
    partial void OnHeadCountChanged();
    partial void OnDiningTypeIdChanging(System.Nullable<int> value);
    partial void OnDiningTypeIdChanged();
    partial void OnGCNumberChanging(string value);
    partial void OnGCNumberChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    #endregion
		
		public tmpRoom()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property", DbType="VarChar(20)")]
		public string Property
		{
			get
			{
				return this._Property;
			}
			set
			{
				if ((this._Property != value))
				{
					this.OnPropertyChanging(value);
					this.SendPropertyChanging();
					this._Property = value;
					this.SendPropertyChanged("Property");
					this.OnPropertyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomId", DbType="Int")]
		public System.Nullable<int> RoomId
		{
			get
			{
				return this._RoomId;
			}
			set
			{
				if ((this._RoomId != value))
				{
					this.OnRoomIdChanging(value);
					this.SendPropertyChanging();
					this._RoomId = value;
					this.SendPropertyChanged("RoomId");
					this.OnRoomIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiningId", DbType="Int")]
		public System.Nullable<int> DiningId
		{
			get
			{
				return this._DiningId;
			}
			set
			{
				if ((this._DiningId != value))
				{
					this.OnDiningIdChanging(value);
					this.SendPropertyChanging();
					this._DiningId = value;
					this.SendPropertyChanged("DiningId");
					this.OnDiningIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WithBreakfast", DbType="Bit")]
		public System.Nullable<bool> WithBreakfast
		{
			get
			{
				return this._WithBreakfast;
			}
			set
			{
				if ((this._WithBreakfast != value))
				{
					this.OnWithBreakfastChanging(value);
					this.SendPropertyChanging();
					this._WithBreakfast = value;
					this.SendPropertyChanged("WithBreakfast");
					this.OnWithBreakfastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeadCount", DbType="Int")]
		public System.Nullable<int> HeadCount
		{
			get
			{
				return this._HeadCount;
			}
			set
			{
				if ((this._HeadCount != value))
				{
					this.OnHeadCountChanging(value);
					this.SendPropertyChanging();
					this._HeadCount = value;
					this.SendPropertyChanged("HeadCount");
					this.OnHeadCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiningTypeId", DbType="Int")]
		public System.Nullable<int> DiningTypeId
		{
			get
			{
				return this._DiningTypeId;
			}
			set
			{
				if ((this._DiningTypeId != value))
				{
					this.OnDiningTypeIdChanging(value);
					this.SendPropertyChanging();
					this._DiningTypeId = value;
					this.SendPropertyChanged("DiningTypeId");
					this.OnDiningTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GCNumber", DbType="VarChar(50)")]
		public string GCNumber
		{
			get
			{
				return this._GCNumber;
			}
			set
			{
				if ((this._GCNumber != value))
				{
					this.OnGCNumberChanging(value);
					this.SendPropertyChanging();
					this._GCNumber = value;
					this.SendPropertyChanged("GCNumber");
					this.OnGCNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(MAX)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
